### ISSUE TITLE
HMR not working

### ISSUE THREAD

**Issue by jasan-s** [jpsierens/webpack-react-redux-react-router#1]
Just clone the repo, ran npm install and then npm start.  HMR not working.

**Comment by jpsierens** [comment]
Thanks for letting me know. It is indeed not working. I'll have a look.

**Comment by jpsierens** [comment]
This is a hard to fix problem it seems... It's coming from react-router. When I remove everything that has to do with the router the hot reloading works fine.

I haven't found a good solution yet, but I have managed to make the page reload when there's a change. I know it's not the same as actually hot reloading it though.

Change your Root.dev.js to this:

``` javascript
import React, { Component, PropTypes } from 'react';
import { Provider } from 'react-redux';
import routes from '../routes';
import DevTools from './DevTools';
import { Router } from 'react-router';

export default class Root extends Component {
    render() {
        const { store, history } = this.props;
        return (
            <Provider store={store}>
                <div>
                    <Router history={history} routes={routes} />
                    <DevTools />
                </div>
            </Provider>
        );
    }
}

if (module.hot) {
    module.hot.decline("../routes.js");
}

Root.propTypes = {
    store: PropTypes.object.isRequired,
    history: PropTypes.object.isRequired
};

```

#https://github.com/reactjs/react-router/issues/2704

**Comment by jpsierens** [comment]
I just changed from react-transform to React Hot Loader 3 and HMR is now working! It still gives the error message about the router not liking being changed though

I took this as an example
https://github.com/gaearon/redux-devtools/tree/master/examples/todomvc
