### ISSUE TITLE
Warning: [react-router] You cannot change <Router routes> warning on file change

### ISSUE THREAD

**Issue by wonbyte** [jpsierens/webpack-react-redux-react-router#10]
When I follow your example and change the "Filter Table" text in App.js to just "Filter" I notice a warning in the console: Warning: [react-router] You cannot change <Router routes>; it will be ignored. I think it has to do with either the routes or the store getting re-rendered in Root by hot-reloading

**Comment by GabeDuarteM** [comment]
+1, this is happening with me too

**Comment by wonbyte** [comment]
See the comment here. Looks like it's an issue with React-Router https://github.com/gaearon/react-hot-loader/issues/454

**Comment by jpsierens** [comment]
Thanks @wonbyte !
