### ISSUE TITLE
Edit/Save drops a notice about react-router

### ISSUE THREAD

**Issue by gabrielmicko** [jpsierens/webpack-react-redux-react-router#11]
Warning: [react-router] You cannot change <Router routes>; it will be ignored

**Comment by jpsierens** [comment]
This is a relationship issue between react-router and HMR, please see:
1) https://github.com/jpsierens/webpack-react-redux/issues/1
2) https://github.com/jpsierens/webpack-react-redux/issues/10

**Comment by gabrielmicko** [comment]
Thank you for the quick response and for the repo, I'll leave it like that.
