### ISSUE TITLE
Server file

### ISSUE THREAD

**Issue by aseem2625** [jpsierens/webpack-react-redux-react-router#17]
Not an issue as such. But a suggestion.
It's a pretty good, clean and good base point for customising-adding complex stuffs. But only things I found missing in this repo is that ```server(express/node)``` file. When you do ```npm run build```, it does creates the bundled files in a ```dist``` folder but routes won't work with them and server is needed to serve those files. Correct me if I'm wrong.
(I'm not talking about the ```./server.js``` file which is using webpackDevServer because it's only for development purposes.)

Cheers

**Comment by jpsierens** [comment]
I get you, but the purpose of this project is: A boilerplate for playing around or a starting point for a project. How you actually want to run the project in production is out of scope for this. I do appreciate you taking the time to write this, thanks!
