### ISSUE TITLE
redux-thunk not in package.json

### ISSUE THREAD

**Issue by calvinw** [jpsierens/webpack-react-redux-react-router#2]
I got a error when npm installing, I think redux-thunk was left out of package.json

**Comment by calvinw** [comment]
Or remove the references in configureStore.prod.js to it.

**Comment by jpsierens** [comment]
Thanks for reporting this. I removed redux-thunk from the project because my simple example doesn't contain any async actions in it. I forgot to remove it for the production files.

**Comment by jpsierens** [comment]
Ok I removed all the references to thunk. Project working now
