### ISSUE TITLE
webpack will recompile on file change on OS X, but not on Linux

### ISSUE THREAD

**Issue by jbeard4** [jpsierens/webpack-react-redux-react-router#21]
I am attempting to use hot-reload. On OS X 10.12, when I run `npm start`, open localhost:3000, and then change App.js, webpack will successfully recompile changes and hot-reload the changes in the browser. But this will fail on Ubuntu 16.04, which does not recompile when when App.js is changed. It appears that webpack-dev-server does not detect changes to App.js

**Comment by helb** [comment]
Common issues:

- not enought 'file watchers' available
- `webpack-dev-server` has problems with some editors (not detecting saves)

More info: https://webpack.github.io/docs/troubleshooting.html#watching

What editor are you using to change the files?

**Comment by jpsierens** [comment]
Have you checked if your paths are correct in a case-sensitive way? Mac doesn't care about case-sensitive paths but linux does. Other than that I'm not sure.
