### ISSUE TITLE
Update to webpack2

### ISSUE THREAD

**Issue by gabrielmicko** [jpsierens/webpack-react-redux-react-router#23]

**Comment by helb** [comment]
I've created a fork with *work-in-progress* webpack 3 migration here: https://github.com/helb/webpack-react-redux/tree/webpack3

No PR yet, still needs some refinement and testing. Feel free to try it out and report any issues you encounter.

```bash
git clone https://github.com/helb/webpack-react-redux
cd webpack-react-redux
git checkout webpack3
npm install # or yarn…
npm start
```

**Comment by jjwilliams42** [comment]
Did you ever finish this fork up @helb ?

**Comment by helb** [comment]
Not really to the point i'd send a MR (yet… i've been without much internet during August), but i'm using it for both personal and work projects.

Some things that are missing:
- compatibility with ESLint 4
- some foundation for tests (i'll probably use Jest)

**Comment by jpsierens** [comment]
Not planning to update the project for now, try @helb 's example
