### ISSUE TITLE
yarn build

### ISSUE THREAD

**Issue by dmpx** [jpsierens/webpack-react-redux-react-router#24]
main.min.js

{"undefined"!=typeof __REACT_HOT_LOADER__&&(__REACT_HOT_LOADER__.register(a,"About","C:/Users/win/Desktop/wrr/app/components/About.js"),__REACT_HOT_LOADER__.register(u,"default","C:/Users/win/Desktop/wrr/app/components/About.js"))})()},

can remove __REACT_HOT_LOADER__?

**Comment by helb** [comment]
Yes, just pass `NODE_ENV=production` to `webpack`:

```
  "scripts": {
    …
    "build": "rimraf dist && cross-env NODE_ENV=production webpack --config ./webpack.production.config.js --progress --profile --colors",
    …  
},
```

([`cross-env`](https://www.npmjs.com/package/cross-env) is often needed to make it work on Windows)

```bash
# counting HOT_LOADER occurrences in the production build:

$ # without NODE_ENV=production:
$ grep -o HOT_LOADER dist/* | wc -l 
$ 36

$ # with NODE_ENV=production:
$ grep -o HOT_LOADER dist/* | wc -l 
$ 0  # nothing :)
```

**Comment by jpsierens** [comment]
Thanks @helb !
