### ISSUE TITLE
Trouble integrating with the 'thunk' middleware

### ISSUE THREAD

**Issue by danieljbruce** [jpsierens/webpack-react-redux-react-router#32]
I want to use thunk middleware so that I can work with APIs and return a function as an action instead of being limited to static objects as actions and synchronous calls. Integrating the thunk middleware leads to errors when trying to use it.

Steps to reproduce error:
1. In the project directory root, open terminal and type 'npm install redux-thunk --save'
2. Also type in 'npm install isomorphic-fetch --save'
3. Create a FetchData.js file in the actions with the following:
```
import fetch from 'isomorphic-fetch';
import filterTable from '../actions/index.js';

export function fetchData() {
    return function(dispatch) {
        return fetch('https://www.googleapis.com/youtube/v3/channels?part=contentDetails&mine=true')
            .then(
                response => response.json(),
                error => console.log('An error occured.', error)
            )
            .then(function(json) {
                console.log(json);
                dispatch(filterTable('a'));
            });
    };
}
```
4. In index.js add the following line to the top:
`import fetchData from './actions/FetchData';`
5. Below `const store = configureStore();` add the following line:
`store.dispatch(fetchData());`

The error that I get is`Uncaught TypeError: (0 , _FetchData2.default) is not a function` when starting the app. It is as if it is trying to create a second version of the function I want to import.

**Comment by danieljbruce** [comment]
Note that configureStore.dev.js changed line `applyMiddleware(middleware)` to `applyMiddleware(middleware, thunk)` and added line `import thunk from 'redux-thunk';` to the top.

**Comment by danieljbruce** [comment]
I found the answer. `import fetchData from './actions/FetchData';` should be `import {fetchData} from './actions/FetchData';`. Note the curly braces.

**Comment by helb** [comment]
…or <code>export <b>default</b> function fetchData() {</code> :)

**Comment by jpsierens** [comment]
Glad you solved it. here's an implementation for async actions if anyone else wants to extend:
https://github.com/jpsierens/todo-app
