### ISSUE TITLE
npm start

### ISSUE THREAD

**Issue by M-Fasciano** [jpsierens/webpack-react-redux-react-router#9]
$ npm start

> webpack-react-redux-react-router@1.0.0 start C:\My_Projects\AQ-R\webpack-react-redux
> node server

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:3000
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1257:14)
    at listen (net.js:1293:10)
    at net.js:1403:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! webpack-react-redux-react-router@1.0.0 start: `node server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webpack-react-redux-react-router@1.0.0 start script 'node server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the webpack-react-redux-react-router package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs webpack-react-redux-react-router
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls webpack-react-redux-react-router
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\My_Projects\AQ-R\webpack-react-redux\npm-debug.log

**Comment by jpsierens** [comment]
It looks like your `3000` port is already in use by something else. Close all your other servers and run `npm start` again

**Comment by M-Fasciano** [comment]
I've done what you have suggested but still got the same issue.

**Comment by M-Fasciano** [comment]
I've tried again today and it's working, weird.
